sudo: false
osx_image: xcode7.3
language: objective-c
rvm: 2.2.4

before_script: bundle install

script:
  - bundle exec rake
  - bundle exec rspec
  - bundle exec rubocop
  - cat /Library/Preferences/SystemConfiguration/preferences.plist
  - security dump-keychain -a /Library/Keychains/System.keychain
