sudo: required
language: objective-c
rvm: 2.2.5

osx_image:
  - xcode8
  - xcode9

before_script:
  - bundle install
  - sudo gem install bundler --no-document
  - sudo bundle install

script:
  - bundle exec rake
  - bundle exec rspec --tag ~sudo
  - sudo bundle exec rspec --tag sudo
  - bundle exec rubocop
